# yaml-language-server: $schema=https://blue-build.org
name: my-dream-os
description: A bulletproof Linux OS for Gamers and Professionals.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - micro
      - steam-devices

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - com.valvesoftware.Steam
          - org.onlyoffice.desktopeditors
      - scope: user
        install: []  
      - type: signing
        no-sign: true
